# Docker Infrastructure (see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ )
sudo: false

language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install flake8 ddt nose --use-mirrors
script:
  - flake8 tests/
  - nosetests

