# Docker Infrastructure (see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ )
sudo: false

# see http://docs.travis-ci.com/user/apt/#Adding-APT-Packages for adding packages in a container build
addons:
    apt:
      packages:
        - devscripts
        - dpkg

language: python
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=pep8
    - python: 2.7
      env: TOX_ENV=py27
    - python: 2.6
      env: TOX_ENV=py26
    - python: 3.4
      env: TOX_ENV=py34

install:
  - pip install tox
script:
  - tox -e $TOX_ENV
